export const COLORS = {
  PRIMARY_BG_START: "#E4F2FC",
  PRIMARY_BG_END: "#728BF31A",
  PRIMARY_BG: "#E4F2FC",
  TITLE_GREY: "#1D1D1F",
  SUBTITLE_GREY: "#6E6E73",
  PRIMARY_BUTTON_COLOR: "#B7C5F9",
  PRIMARY_BUTTON_TEXT: "#101073",
  PRIMARY_BUTTON_TEXT_DARK: "#364153",
  PRIMARY_BORDER_COLOR: "#101073",
  CARD_BG: "#FBFBFD",
  TAG_BG: "#F2F4FE",
  PRIMARY_BORDER_GREY: "#E5E5E7",
  NOTIFICATION_BG: "#F5D76E",
  NO_ENABLE_ICON: "#8E8E93",
  PRYMARY_SVG_COLOR: "#C7C7CC",
  PRYMARY_RED_COLOR: "#FF3B30",
  PRIMARY_PLACEHOLDER: "#1D1D1F80",
  ICON_GREY_COLOR: "#6E6E73",
  SEMI_BLUE_COLOR: "#B7C5F9",
  SVG_BG: "#F9F9F9",
  BG_CARD_ACTIVE: "#F2F2F7",
  LIGHT_GREY: "#F5F5F7",
  SUCCESS: "#4CAF50",
  ERROR: "#F44336",
  WARNING: "#FF9800",
  INFO: "#2196F3",
};

export const GRADIENT_PRYMARY_BG = {
  PRYMARY: {
    LIST_COLORS: ["#E4F2FC", "#728BF31A"] as const,
    COUNT_COLORS: [0, 1] as const,
  },
} as const;

export const GRADIENT_PRYMARY_BG_FOUR = {
  PRYMARY: {
    LIST_COLORS: ["#E4F2FC", "#728cf377"] as const,
    COUNT_COLORS: [0.1, 0.9] as const,
  },
} as const;
export const GRADIENT_PRYMARY_BG_FIVE = {
  PRYMARY: {
    LIST_COLORS: ["#728cf34e", "#728cf3b0"] as const,
    COUNT_COLORS: [0.1, 0.9] as const,
  },
} as const;

export const GRADIENT_PRYMARY_BG_REVERSE = {
  PRYMARY: {
    LIST_COLORS: ["#718AF3", "#E4F2FC"] as const,
    COUNT_COLORS: [0.33, 0.77] as const,
  },
} as const;
